### ISSUE TITLE
Any plan to port it to GNOME 44?

### ISSUE THREAD

**Issue by iadegesso** [malko/battery-indicator-upower#7]
Hi,
as in the subject, is there any news about a port to GNOME43/44.x ?

Iade

**Comment by malko** [comment]
Hi @iadegesso,

I am tied to gnome42 for now, and have no test env for 43/44. I think it should work on 43, and that's why the metadata.json already announce shell-version 43. If you can confirm that it works out of the box with version 44 of gnome, I'll be pleased to add 44 to the list. 
I'm using linux for more than 20 years now, so you can be confident than when I'll upgrade my env to newer gnome version I'll update to that version (which will occur shortly after an ubuntu LTS release). 
Is this answer is ok for you ? Are you in need for a specific version support before that ?

**Comment by iadegesso** [comment]
> Hi @iadegesso,
> 
> I am tied to gnome42 for now, and have no test env for 43/44. I think it should work on 43, and that's why the metadata.json already announce shell-version 43. If you can confirm that it works out of the box with version 44 of gnome, I'll be pleased to add 44 to the list. I'm using linux for more than 20 years now, so you can be confident than when I'll upgrade my env to newer gnome version I'll update to that version (which will occur shortly after an ubuntu LTS release). Is this answer is ok for you ? Are you in need for a specific version support before that ?

I'm running GNOME 44.1 on my Gentoo... I tryed to force compatibility in metadata.json but the extension falls into an error state... _this.aggregateMenu in undefined_

Iade

**Comment by malko** [comment]
What is weird is I don't see any reference to aggregateMenu in the extension code. 
I'm sorry but without a gnome 44 computer at hand I can't investigate this. You will have to wait either for a PR or for me upgrading my computers which won't be before next ubuntu LTS. In case you can gather more complete stack trace of the error I'll have a look again. 
Thanks for report anyway

**Comment by malko** [comment]
Support was just added for gnome 45 and 46, no planned version to support gnome 44.
